BeginASPdotNET/BeginASPdotNET/Models/SinhVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeginASPdotNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public string SotheSV { get; set; }
        public string NameSV { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<double> DTB { get; set; }
        public int ID_Lop { get; set; }
        public Nullable<bool> CMND { get; set; }
        public Nullable<bool> HocBa { get; set; }
        public Nullable<bool> THPT { get; set; }
        public Nullable<bool> Gender { get; set; }
    
        public virtual LopSV LopSV { get; set; }
    }
}

BeginASPdotNET/BeginASPdotNET/Controllers/SinhViensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BeginASPdotNET.Models;

namespace BeginASPdotNET.Controllers
{
    public class SinhViensController : Controller
    {
        private Entities db = new Entities();

        // GET: SinhViens

        public ActionResult Index(string txt,int Lop_ID=0) //view len man hinh danh sach cac sinh vien
        {
            // int ID_Lop=0 đối số mặc định(mặc định khi gọi hàm này ko truyên id mặ định bàng 0, có thể ko cần truyền giá cho id nhưng ưu tiên giá trị truyền vào)
            //var sinhViens = db.SinhViens.Include(s => s.LopSV);
            //txt -> tìm kiếm SV có NameSV chứa txt
            //Lop_ID -> tìm kiếm SV có ID_Lop==Lop_ID
            var listLop = db.LopSVs.Select(p => p);
            ViewBag.Lop_ID = new SelectList(listLop,"ID_Lop","NameLop");// truyền tên thuộc tính khóa chính ID_Lop,NameLop
            var listSV = db.SinhViens.Select(p => p);
            if (!String.IsNullOrEmpty(txt))
            {
                listSV = listSV.Where(p => p.NameSV.Contains(txt));
            }
            if (Lop_ID != 0)
            {
                listSV = listSV.Where(p => p.ID_Lop == Lop_ID);
            }
            return View(listSV);
            
        }

        // GET: SinhViens/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SinhVien sinhVien = db.SinhViens.Find(id);
            if (sinhVien == null)
            {
                return HttpNotFound();
            }
            return View(sinhVien);
        }

        // GET: SinhViens/Create
        public ActionResult Create()
        {
            ViewBag.ID_Lop = new SelectList(db.LopSVs, "ID_Lop", "NameLop");
            return View();
        }

        // POST: SinhViens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SotheSV,NameSV,Birthday,DTB,ID_Lop,CMND,HocBa,THPT,Gender")] SinhVien sinhVien)
        {
            if (ModelState.IsValid)
            {
                db.SinhViens.Add(sinhVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Lop = new SelectList(db.LopSVs, "ID_Lop", "NameLop", sinhVien.ID_Lop);
            return View(sinhVien);
        }

        // GET: SinhViens/Edit/5
        public ActionResult Edit(string id) // tra ve trang view cua Client (MEthod Get)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SinhVien sinhVien = db.SinhViens.Find(id); // get doi tuong sinh vien can edit
            if (sinhVien == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Lop = new SelectList(db.LopSVs, "ID_Lop", "NameLop", sinhVien.ID_Lop);
            return View(sinhVien);
        }

        // POST: SinhViens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SotheSV,NameSV,Birthday,DTB,ID_Lop,CMND,HocBa,THPT,Gender")] SinhVien sinhVien)
        {
            //page update thong tin sinh vien tren Server (MEthod POST)
            if (ModelState.IsValid)
            {
                db.Entry(sinhVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Lop = new SelectList(db.LopSVs, "ID_Lop", "NameLop", sinhVien.ID_Lop);
            return View(sinhVien);
        }

        // GET: SinhViens/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SinhVien sinhVien = db.SinhViens.Find(id);
            if (sinhVien == null)
            {
                return HttpNotFound();
            }
            return View(sinhVien);
        }

        // POST: SinhViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SinhVien sinhVien = db.SinhViens.Find(id);
            db.SinhViens.Remove(sinhVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BeginASPdotNET/BeginASPdotNET/Views/SinhViens/Create.cshtml
@model BeginASPdotNET.Models.SinhVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SinhVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SotheSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SotheSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SotheSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DTB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DTB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DTB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Lop, "ID_Lop", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Lop", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Lop, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CMND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CMND)
                    @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HocBa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.HocBa)
                    @Html.ValidationMessageFor(model => model.HocBa, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.THPT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.THPT)
                    @Html.ValidationMessageFor(model => model.THPT, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Gender)
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BeginASPdotNET/BeginASPdotNET/Views/SinhViens/Delete.cshtml
@model BeginASPdotNET.Models.SinhVien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SinhVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameSV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameSV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DTB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DTB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HocBa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HocBa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.THPT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.THPT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LopSV.NameLop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LopSV.NameLop)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BeginASPdotNET/BeginASPdotNET/Views/SinhViens/Details.cshtml
@model BeginASPdotNET.Models.SinhVien

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SinhVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NameSV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameSV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DTB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DTB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CMND)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HocBa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HocBa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.THPT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.THPT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LopSV.NameLop)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LopSV.NameLop)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SotheSV }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BeginASPdotNET/BeginASPdotNET/Views/SinhViens/Edit.cshtml
@model BeginASPdotNET.Models.SinhVien

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SinhVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SotheSV)

        <div class="form-group">
            @Html.LabelFor(model => model.NameSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DTB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DTB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DTB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Lop, "ID_Lop", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Lop", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Lop, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CMND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CMND)
                    @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HocBa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.HocBa)
                    @Html.ValidationMessageFor(model => model.HocBa, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.THPT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.THPT)
                    @Html.ValidationMessageFor(model => model.THPT, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Gender)
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BeginASPdotNET/BeginASPdotNET/Views/SinhViens/Index.cshtml
@model IEnumerable<BeginASPdotNET.Models.SinhVien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p><!-- ACtion link: 2 tham số , tương tự như ahref, Create New là tên đường link, còn create là ActionResult nào của controller-->
    @Html.ActionLink("Create New", "Create")  
    @using (Html.BeginForm("Index","SinhViens",FormMethod.Get))// 3 tham so: action result Index,Controler SInhVoens, method get
    {
        <p>
            Title: @Html.TextBox("txt")--- Class: @Html.DropDownList("Lop_ID","All")
            <input type="submit" value="Tìm kiếm"/>
        </p>
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NameSV)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DTB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CMND)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HocBa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.THPT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LopSV.NameLop)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NameSV)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthday)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DTB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CMND)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HocBa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.THPT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LopSV.NameLop)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SotheSV }) |
            @Html.ActionLink("Details", "Details", new { id=item.SotheSV }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SotheSV })
        </td>
    </tr>
}

</table>